--- 
swagger: "2.0"
consumes:
- app/com.hemmitkerrai.todo
info:
  title: Hemm's Todo App
  version: 1.0.0
paths: {}
produces:
- app/com.hemmitkerrai.todo
schemes:
- http

paths:
  /:
    get:
      tags:
        - todos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - todos
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        default:
          description: generic creation error response
          schema:
            $ref: "#/definitions/error"

  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - todos
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: generic update error response
          schema:
            $ref: "#/definitions/error"
    
    delete:
      tags:
        - todos
      responses:
        204:
          description: Deleted
        default:
          description: generic deletion error response
          schema:
            $ref: "#/definitions/error"
  
    

definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string