// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Hemm's Todo App
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - app/com.hemmitkerrai.todo
//
//  Produces:
//    - app/com.hemmitkerrai.todo
//
// swagger:meta
package restapi
